#!/usr/bin/env bash

DEFCONFIG="arch/arm64/configs/gki_defconfig"

echo "⚙️ Added KSU & SuSFS configuration"

cat >> $DEFCONFIG <<EOF
CONFIG_KSU=y
CONFIG_KPM=y
CONFIG_KSU_MULTI_MANAGER_SUPPORT=y
CONFIG_KPROBES=y
CONFIG_KPROBE_EVENTS=y
EOF

if [ "$KSU" == "SukiSU" ]; then
    if [ "$KSU_SUSFS" = "true" ]; then
        echo "🔧 Mode: SukiSU + SuSFS Enabled"
        cat >> $DEFCONFIG <<EOF
CONFIG_KSU_SUSFS=y
EOF
    else
        echo "🔧 Mode: SukiSU Standard (No SuSFS)"
    fi

elif [ "$KSU_SUSFS" = "true" ]; then
  echo "🔧 Mode: SuSFS Hook Enabled"
  cat >> $DEFCONFIG <<EOF
CONFIG_KSU_SUSFS=y
CONFIG_KSU_SUSFS_HAS_MAGIC_MOUNT=y
CONFIG_KSU_SUSFS_SUS_PATH=y
CONFIG_KSU_SUSFS_SUS_MOUNT=y
CONFIG_KSU_SUSFS_SUS_KSTAT_SPOOF_GENERIC=y
CONFIG_KSU_SUSFS_SUS_KSTAT=y
CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSU_DEFAULT_MOUNT=y
CONFIG_KSU_SUSFS_AUTO_ADD_SUS_BIND_MOUNT=y
CONFIG_KSU_SUSFS_AUTO_ADD_SUS_KSTAT=y
CONFIG_KSU_SUSFS_SUS_OVERLAYFS=n
CONFIG_KSU_SUSFS_TRY_UMOUNT=n
CONFIG_KSU_SUSFS_AUTO_ADD_TRY_UMOUNT_FOR_BIND_MOUNT=n
CONFIG_KSU_SUSFS_SPOOF_UNAME=y
CONFIG_KSU_SUSFS_ENABLE_LOG=y
CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=y
CONFIG_KSU_SUSFS_SPOOF_CMDLINE_OR_BOOTCONFIG=y
CONFIG_KSU_SUSFS_OPEN_REDIRECT=y
CONFIG_KSU_MANUAL_HOOK=n
CONFIG_KSU_HAS_MANUAL_HOOK=n
EOF

else
  echo "🔧 Mode: Kprobes Hook Standard"
  cat >> $DEFCONFIG <<EOF
CONFIG_KSU_SUSFS=n
CONFIG_KSU_SUSFS_SUS_SU=n
CONFIG_KSU_MANUAL_HOOK=n
CONFIG_KSU_HAS_MANUAL_HOOK=n
CONFIG_KSU_SUSFS_HIDE_KSU_SUSFS_SYMBOLS=n
CONFIG_KSU_SYSCALL_HOOK=n
EOF
fi

echo "⚙️ Adding Universal Performance Tuning"
cat >> $DEFCONFIG <<EOF
CONFIG_TMPFS_XATTR=y
CONFIG_TMPFS_POSIX_ACL=y
CONFIG_IP_NF_TARGET_TTL=y
CONFIG_TCP_CONG_ADVANCED=y
CONFIG_TCP_CONG_WESTWOOD=y
# CONFIG_TCP_CONG_BBR is not set
CONFIG_DEFAULT_WESTWOOD=y
CONFIG_NET_SCH_FQ=y
# CONFIG_IOSCHED_BFQ is not set
# CONFIG_BFQ_GROUP_IOSCHED is not set
CONFIG_DEFAULT_ADIOS=y
CONFIG_MQ_IOSCHED_ADIOS=y
CONFIG_DEFAULT_ADIOS=y
CONFIG_MQ_DEADLINE=y
CONFIG_DEFAULT_MQ_DEADLINE=y
# CONFIG_DEFAULT_FQ_CODEL is not set
CONFIG_HZ_300=y
CONFIG_HZ=300
CONFIG_CPU_FREQ=y
CONFIG_SWAP=y
CONFIG_CPU_FREQ_GOV_SCHEDUTIL=y
CONFIG_CPU_FREQ_GOV_ONDEMAND=y
EOF

if [ "$KVER" == "5.10" ]; then
  echo "⚙️ Adding VorteX Native C-Script Dependencies (5.10 Only)"
  cat >> $DEFCONFIG <<EOF
CONFIG_ANDROID_LOW_MEMORY_KILLER=y
CONFIG_DEVFREQ_GOV_PERFORMANCE=y
EOF

  echo "⚙️ Added LTO & Compiler Optimization (KVER 5.10 Only)"
  cat >> $DEFCONFIG <<EOF
CONFIG_LTO=y
CONFIG_LTO_CLANG=y
CONFIG_ARCH_SUPPORTS_LTO_CLANG=y
CONFIG_ARCH_SUPPORTS_LTO_CLANG_THIN=y
CONFIG_HAS_LTO_CLANG=y
# CONFIG_LTO_NONE is not set
# CONFIG_LTO_CLANG_FULL is not set
CONFIG_LTO_CLANG_THIN=y
EOF
else
  echo "⚙️ LTO Optimization skipped (For KVER 6.1 & 6.6)"
fi
